In [20]:
import csv
import random
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [2]:
data = []
with open('C:/Users/User/Desktop/csv/PytorchGen-master/original_data/creditcard_1_train_no_label.csv') as csvfile:
    csv_reader = csv.reader(csvfile)  # 使用csv.reader讀取csvfile中的檔案
    birth_header = next(csv_reader)  # 讀取第一行每一列的標題
    for row in csv_reader:  # 將csv 檔案中的資料儲存到birth_data中
        data.append(row)

data = [[float(x) for x in row] for row in data]  # 將資料從string形式轉換為float形式

data = np.array(data)  # 將list陣列轉化成array陣列便於檢視資料結構

data
# type(data[0][0])

array([[-0.48675026,  0.28920009, -0.28233011, ...,  0.0430662 ,
        -0.25992896, -0.10776391],
       [-0.19239733,  0.16567393, -0.08530844, ...,  0.22122762,
        -0.02522442,  0.31683638],
       [-0.16724549,  0.16868026, -0.1552885 , ..., -0.07732387,
        -0.02215347,  0.03935308],
       ...,
       [-0.4604465 ,  0.03412065, -0.35279859, ..., -0.07884899,
        -0.06103365,  0.0435543 ],
       [-0.72785331,  0.13159553, -0.5343746 , ...,  0.01558436,
        -0.15307746, -0.10566456],
       [-0.22150757,  0.02981066, -0.09041667, ..., -0.09210756,
         0.05448834, -0.0171239 ]])

In [3]:
len(data)
import pandas as pd

df = pd.DataFrame(data)
df.columns = ['V14', 'V4', 'V10', 'V17', 'Time', 'V12', 'V26', 'Amount', 'V21', 'V8', 'V11', 'V7', 'V28', 'V19', 'V3', 'V22', 'V6', 'V20', 'V27', 'V16', 'V13', 'V25', 'V24', 'V18', 'V2', 'V1', 'V5', 'V15', 'V9', 'V23']

df

V14        V4       V10       V17      Time       V12       V26  \
0   -0.486750  0.289200 -0.282330 -0.393922 -0.247642 -0.310684  0.037754   
1   -0.192397  0.165674 -0.085308  0.082249 -0.247328 -0.054504 -0.030431   
2   -0.167245  0.168680 -0.155288 -0.664896 -0.228307 -0.701909 -0.114240   
3   -0.768027  0.193941 -0.489101 -1.750109 -0.216275 -1.167150 -0.138471   
4   -0.689627  0.342310 -0.249236  0.934647 -0.213734 -0.493429  0.119810   
..        ...       ...       ...       ...       ...       ...       ...   
487 -0.756022  0.126696 -0.569201 -0.635560  0.144855 -0.579770  0.166560   
488 -0.591118  0.102309 -0.329187 -0.454601  0.145833 -0.331741  0.156238   
489 -0.460446  0.034121 -0.352799 -0.700090  0.145852 -0.297335  0.099624   
490 -0.727853  0.131596 -0.534375 -0.641695  0.148783 -0.538410  0.128105   
491 -0.221508  0.029811 -0.090417  0.124433  0.150604  0.077184 -0.060863   

       Amount       V21        V8  ...       V13       V25       V24  \
0   -0.193722  0.094555  0.144351  ... -0.060452  0.008706  0.053636   
1    0.189954  0.120816 -0.008240  ...  0.068730  0.055245 -0.049243   
2    0.141734 -0.052941 -0.042885  ...  0.002341 -0.030980 -0.014648   
3    0.056706  0.104797 -0.027163  ...  0.018739  0.049827 -0.008980   
4   -0.151326 -0.068375 -0.053049  ...  0.148762  0.294409 -0.273575   
..        ...       ...       ...  ...       ...       ...       ...   
487  0.171350  0.142064  0.071744  ... -0.125453  0.106220 -0.049425   
488 -0.159145  0.067903  0.024832  ... -0.080495  0.103129 -0.013595   
489  0.073447  0.137200  0.125374  ... -0.042546 -0.146414  0.005359   
490  0.143008  0.106561  0.109542  ... -0.114516 -0.065012 -0.030788   
491  0.037079 -0.029343 -0.008302  ...  0.038654  0.061865 -0.075459   

          V18        V2        V1        V5       V15        V9       V23  
0   -0.002294  0.135631 -0.128532 -0.043418  0.043066 -0.259929 -0.107764  
1    0.210910 -0.221716 -0.168832  0.112307  0.221228 -0.025224  0.316836  
2   -0.320343  0.122150 -0.128043 -0.068195 -0.077324 -0.022153  0.039353  
3   -0.628238  0.094113 -0.243471 -0.093556 -0.000846 -0.023047 -0.101075  
4    0.372107  0.210310  0.066902  0.299673 -0.037555 -0.120257 -0.151948  
..        ...       ...       ...       ...       ...       ...       ...  
487 -0.161184  0.077837 -0.107352 -0.129828  0.044391 -0.193706  0.146979  
488 -0.084495  0.089288  0.074855  0.036412 -0.067921 -0.105657 -0.034067  
489 -0.062283  0.077886 -0.038373 -0.092928 -0.078849 -0.061034  0.043554  
490 -0.181131  0.040083 -0.172706 -0.069766  0.015584 -0.153077 -0.105665  
491  0.146292  0.010192  0.108658  0.095041 -0.092108  0.054488 -0.017124  

[492 rows x 30 columns]

In [4]:
print(len(df.values))
type(df.values)


492


numpy.ndarray

In [5]:
class Smote:
    def __init__(self,samples,N=10,k=5):
        self.n_samples,self.n_attrs=samples.shape
        self.N=N
        self.k=k
        self.samples=samples
        self.newindex=0
       # self.synthetic=np.zeros((self.n_samples*N,self.n_attrs))

    def over_sampling(self):
        N=int(self.N/100)
        self.synthetic = np.zeros((self.n_samples * N, self.n_attrs))
        neighbors=NearestNeighbors(n_neighbors=self.k).fit(self.samples)
        print('neighbors',neighbors)
        for i in range(len(self.samples)):
            nnarray=neighbors.kneighbors(self.samples[i].reshape(1,-1),return_distance=False)[0]
            #print nnarray
            self._populate(N,i,nnarray)
        return self.synthetic


    # for each minority class samples,choose N of the k nearest neighbors and generate N synthetic samples.
    def _populate(self,N,i,nnarray):
        for j in range(N):
            nn=random.randint(0,self.k-1)
            dif=self.samples[nnarray[nn]]-self.samples[i]
            gap=random.random()
            self.synthetic[self.newindex]=self.samples[i]+gap*dif
            self.newindex+=1


In [21]:
# a=np.array(df)
a = data
N_100_K_5=Smote(a,N=100,k=5)
N_100_K_5.over_sampling()

neighbors NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)


array([[-0.48675026,  0.28920009, -0.28233011, ...,  0.0430662 ,
        -0.25992896, -0.10776391],
       [-0.19239733,  0.16567393, -0.08530844, ...,  0.22122762,
        -0.02522442,  0.31683638],
       [-0.17688298,  0.17146424, -0.15848701, ..., -0.07311879,
        -0.02653308,  0.03887493],
       ...,
       [-0.58516095,  0.11017297, -0.39474449, ..., -0.18716959,
        -0.10000291, -0.14263132],
       [-0.72653201,  0.13950272, -0.53139767, ...,  0.02053803,
        -0.1558008 , -0.105476  ],
       [-0.21594708,  0.00662734, -0.11776589, ..., -0.08591487,
         0.04164455,  0.0303789 ]])

In [23]:
N_100_K_8=Smote(a,N=100,k=8)
N_100_K_8.over_sampling()

neighbors NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                 radius=1.0)


array([[-6.23809676e-01,  2.80780299e-01, -3.14519567e-01, ...,
         3.68765359e-02, -1.81040194e-01, -2.58996973e-03],
       [-8.78637155e-02,  1.31041123e-01, -4.41968717e-02, ...,
         2.33507846e-01, -3.33671557e-02,  1.89496160e-01],
       [-1.74624203e-01,  1.68878936e-01, -1.59311431e-01, ...,
        -6.92023411e-02, -2.52905234e-02,  3.95503725e-02],
       ...,
       [-4.48227699e-01,  9.21498264e-02, -3.56304086e-01, ...,
        -2.83964096e-04, -1.05383037e-01,  2.95549504e-02],
       [-5.43597844e-01,  2.10072031e-01, -4.09170066e-01, ...,
         1.76654776e-01, -1.82925945e-01, -3.20363568e-02],
       [-2.21507572e-01,  2.98106557e-02, -9.04166693e-02, ...,
        -9.21075648e-02,  5.44883362e-02, -1.71239015e-02]])

In [30]:
N_150_K_10=Smote(a,N=150,k=10)
N_150_K_10.over_sampling()


neighbors NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                 radius=1.0)


array([[-0.52628374,  0.23675804, -0.21985082, ...,  0.02528523,
        -0.19052225, -0.07236346],
       [-0.19239733,  0.16567393, -0.08530844, ...,  0.22122762,
        -0.02522442,  0.31683638],
       [-0.43222727,  0.24522526, -0.24323116, ...,  0.03829429,
        -0.14257043,  0.02620638],
       ...,
       [-0.46384802,  0.03692279, -0.35481102, ..., -0.07618063,
        -0.06614689,  0.03767521],
       [-0.73399398,  0.14712293, -0.53319433, ...,  0.01195308,
        -0.16697189, -0.08585523],
       [-0.18615153,  0.03435161, -0.09717925, ..., -0.01697683,
         0.02952235, -0.04073585]])

In [33]:
N_150_K_10.over_sampling()

neighbors NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                 radius=1.0)


IndexError: index 492 is out of bounds for axis 0 with size 492